spring:
  application:
    name:tlias-web-management

  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1819173541Kk
  servlet:
    multipart:
      max-file-size: 10MB #最大单个文件大小
      max-request-size: 10MB #最大请求大小（包括文件和表单数据）

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: this-is-dyy-bucket
    region: cn-beijing